# Site settings
title: Huleos Framework
email: 
description: Huleos is a small “mobile first” CSS framework, with useful default styles, and a responsive grid system.
url: "http://huleos.github.io/huleos"
huleos_version: v0.1.1

# Build settings
markdown: kramdown

# Customs
permalink: none
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
        - "assets/css/style.css"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
sass:
    sass_dir: assets/sass
    style: :compressed